// List of Indian states
const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Puducherry",
  "Chandigarh",
]

// Mock event data
const mockEvents = [
  {
    id: "1",
    title: "Summer Music Festival 2024",
    description: "Join us for an unforgettable night of music featuring top artists from around the world.",
    date: "2024-07-15",
    time: "18:00",
    venue: "Central Park Amphitheater",
    location: "New York, NY",
    price: 89,
    category: "Music",
    rating: 4.8,
    attendees: 2500,
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
  },
  {
    id: "2",
    title: "Tech Innovation Conference",
    description: "Discover the latest trends in technology and network with industry leaders.",
    date: "2024-08-22",
    time: "09:00",
    venue: "Convention Center",
    location: "San Francisco, CA",
    price: 299,
    category: "Technology",
    rating: 4.9,
    attendees: 1200,
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
  },
  {
    id: "3",
    title: "Food & Wine Tasting",
    description: "Experience exquisite cuisine and fine wines from renowned chefs and sommeliers.",
    date: "2024-06-30",
    time: "19:30",
    venue: "Grand Hotel Ballroom",
    location: "Chicago, IL",
    price: 125,
    category: "Food & Drink",
    rating: 4.7,
    attendees: 300,
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
  },
  {
    id: "4",
    title: "Art Gallery Opening",
    description: "Celebrate contemporary art with an exclusive gallery opening featuring emerging artists.",
    date: "2024-07-08",
    time: "18:00",
    venue: "Modern Art Museum",
    location: "Los Angeles, CA",
    price: 45,
    category: "Arts & Culture",
    rating: 4.6,
    attendees: 150,
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
  },
  {
    id: "5",
    title: "Marathon Training Workshop",
    description: "Professional training session for marathon preparation with expert coaches.",
    date: "2024-07-20",
    time: "07:00",
    venue: "City Sports Complex",
    location: "Boston, MA",
    price: 75,
    category: "Sports & Fitness",
    rating: 4.5,
    attendees: 80,
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
  },
  {
    id: "6",
    title: "Business Networking Mixer",
    description: "Connect with professionals and entrepreneurs in a relaxed networking environment.",
    date: "2024-08-05",
    time: "18:30",
    venue: "Rooftop Lounge",
    location: "Miami, FL",
    price: 35,
    category: "Business",
    rating: 4.4,
    attendees: 200,
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
  },
  {
    id: "7",
    title: "Jazz Night Under the Stars",
    description: "An intimate evening of smooth jazz in a beautiful outdoor setting.",
    date: "2024-08-10",
    time: "20:00",
    venue: "Riverside Park",
    location: "New York, NY",
    price: 65,
    category: "Music",
    rating: 4.7,
    attendees: 400,
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
  },
  {
    id: "8",
    title: "Digital Marketing Summit",
    description: "Learn the latest digital marketing strategies from industry experts.",
    date: "2024-09-05",
    time: "09:00",
    venue: "Tech Hub",
    location: "San Francisco, CA",
    price: 199,
    category: "Technology",
    rating: 4.8,
    attendees: 800,
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
  },
]

export { indianStates, mockEvents }; 